services:
  local_project:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=local_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_project_data:/var/lib/postgresql/data/
    ports:
      - '5434:5432'
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
  web:
    tty: true
    restart: always
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      SSH_KNOWN_HOSTS: ${SSH_KNOWN_HOSTS}
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: local_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      redis:
        condition: service_healthy
      local_project:
        condition: service_started
    ports:
      - "8001:8000"
    volumes:
      - .:/code
  celery:
    tty: true
    restart: always
    build: .
    working_dir: /code
    command: celery -A sentry_job.monitoring_jobs.celery worker
    environment:
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      SSH_KNOWN_HOSTS: ${SSH_KNOWN_HOSTS}
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DB: local_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/code
    depends_on:
      redis:
        condition: service_healthy
      local_project:
        condition: service_started
  celery-beat:
    build: .
    working_dir: /code
    command: celery -A sentry_job.monitoring_jobs beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=sentry_job.settings
    depends_on:
      redis:
        condition: service_healthy
      local_project:
        condition: service_started

volumes:
  local_project_data: